apiVersion: v2
name: elastic-operator
version: 9.1.0
appVersion: 9.0.5
dependencies:
  - name: eck-operator
    repository: https://helm.elastic.co
    version: 3.0.0
description: |
  Elasticsearch + filebeat + kibana with default common used indexes and Index Lifecycle Management.
  It comes also with a backup functionality. This is the version using ECK-operator to deploy and monitor the stack.
