apiVersion: v2
dependencies:
  - name: akhq
    repository: https://akhq.io/
    version: 0.3.1
description: Kafka GUI for Apache KafkaÂ® to manage topics, topics data, consumers group, schema registry, connect and more...
name: akhq
version: 0.3.3

