apiVersion: v2
description: |
  This chart deploys common `CustomResourceDefinitions` for iits-consulting only projects.
  With this we avoid a typical catch-22, e.g. where you can not use `traefik`
  `IngressRoute` before you deploy `traefik` and such.
  You could also use sync-waves and other mechanism, but it creates a lot of complexity
  and a huge dependency graph.
name: crds
version: 1.5.1
