apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: modsecurity-crs-waf
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: disallow-host-path
      ruleNames:
        - host-path
    - policyName: enforce-security-context
      ruleNames:
        - add-pod-security-context
    - policyName: require-run-as-non-root-user
      ruleNames:
        - run-as-non-root-user
    - policyName: require-run-as-nonroot
      ruleNames:
        - run-as-non-root
    - policyName: restrict-seccomp-strict
      ruleNames:
        - check-seccomp-strict
    - policyName: restrict-volume-types
      ruleNames:
        - restricted-volumes
        - autogen-restricted-volumes
    - policyName: disallow-capabilities-strict
      ruleNames:
        - require-drop-all
    - policyName: disallow-privilege-escalation
      ruleNames:
        - privilege-escalation
  match:
    any:
      - resources:
          kinds:
            - Pod
          names:
            - modsecurity-crs-waf*
          namespaces:
            - routing