apiVersion: v2
description: |
  This chart is used to create content objects for ArgoCD like Applications, AppProjects and related K8s secrets for the repo configuration.

  Usage example for terraform:

  ```hcl
  resource "helm_release" "argocd-apps" {
    name                  = "argocd-apps"
    repository            = "https://charts.iits.tech"
    chart                 = "argocd-apps"
    version               = "2.0.2"
    namespace             = "argocd"
    create_namespace      = true
    wait                  = true
    atomic                = true
    timeout               = 900 // 15 Minutes
    render_subchart_notes = true
    dependency_update     = true
    wait_for_jobs         = true
    set_sensitive {
      name  = "projects.app-charts.git.password"
      value = var.git_token
    }
    values                = [
      yamlencode({
        projects = {
          infrastructure-charts = {
            tofuValues = {
              projectValues = {
                # Set this to enable stage based values-$STAGE.yaml file
                stage        = var.stage
                # Example values which are handed down to the project. Like this you can hand over information from terraform to argo-cd
                rootDomain  = var.domain_name
              }
            }
            git = {
              repoUrl  = "https://github.com/iits-consulting/otc-infrastructure-charts-template"
            }
          }
        }
      })
    ]
  }
  ```

  In the project https://github.com/iits-consulting/otc-infrastructure-charts-template it expects a helm chart
  named infrastructure-charts and will install everything from there.

name: argocd-apps
version: 2.0.2
