apiVersion: v2
dependencies:
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 22.1.5
description: |
  Apache Kafka is an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications.
  This chart wraps the `kafka` chart from bitnami and defines a few sensible defaults.
name: kafka
version: 22.2.0
appVersion: 22.1.5
