apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.elasticsearch.backup.job.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: {{ .Values.elasticsearch.backup.job.name }}
      labels:
        job: {{ .Values.elasticsearch.backup.job.name }}
        app: {{ .Chart.Name }}
    spec:
      template:
        metadata:
          name: {{ .Values.elasticsearch.backup.job.name }}
          labels:
            job: {{ .Values.elasticsearch.backup.job.name }}
            app: {{ .Chart.Name }}
        spec:
          containers:
            - name: {{ .Values.elasticsearch.backup.job.name }}
              image: {{.Values.elasticsearch.backup.job.image}}
              command: ["/bin/sh","-c"]
              args: ["/opt/sh/snapshot.sh"]
              env:
                - name: HOST
                  value: {{.Values.elasticsearch.backup.snapshotEnv.host | quote}}
                - name: LOCAL_PORT
                  value: {{.Values.elasticsearch.backup.snapshotEnv.port | quote}}
                - name: SNAPSHOT_REPOSITORY
                  value: {{.Values.elasticsearch.backup.snapshotEnv.snapshotRepository | quote}}
                - name: SNAPSHOT_NAME
                  value: {{.Values.elasticsearch.backup.snapshotEnv.snapshotName | quote}}
              volumeMounts:
                - name: {{.Values.elasticsearch.backup.job.configName}}
                  mountPath: /opt/sh
          volumes:
            - name: {{.Values.elasticsearch.backup.job.configName}}
              configMap:
                name: {{.Values.elasticsearch.backup.job.configName}}
                defaultMode: 0777
          restartPolicy: Never
  schedule: {{ .Values.elasticsearch.backup.job.schedule | quote }}