apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
# Setting a blank data again will wipe admin password/key/cert
data:
  {{- if .Values.configs.secret.githubSecret }}
  webhook.github.secret: {{ .Values.configs.secret.githubSecret | b64enc }}
  {{- end }}
  {{- if .Values.configs.secret.gitlabSecret }}
  webhook.gitlab.secret: {{ .Values.configs.secret.gitlabSecret | b64enc }}
  {{- end }}
  {{- if .Values.configs.secret.bitbucketServerSecret }}
  webhook.bitbucketserver.secret: {{ .Values.configs.secret.bitbucketServerSecret | b64enc }}
  {{- end }}
  {{- if .Values.configs.secret.bitbucketUUID }}
  webhook.bitbucket.uuid: {{ .Values.configs.secret.bitbucketUUID | b64enc }}
  {{- end }}
  {{- if .Values.configs.secret.gogsSecret }}
  webhook.gogs.secret: {{ .Values.configs.secret.gogsSecret | b64enc }}
  {{- end }}
  {{- if .Values.configs.secret.argocdServerTlsConfig }}
  tls.key: {{ .Values.configs.secret.argocdServerTlsConfig.key | b64enc }}
  tls.crt: {{ .Values.configs.secret.argocdServerTlsConfig.crt | b64enc }}
  {{- end }}
  {{- if .Values.configs.secret.argocdServerAdminPassword }}
  admin.password: {{ .Values.configs.secret.argocdServerAdminPassword | b64enc }}
  admin.passwordMtime: {{ default (dateInZone "2006-01-02T15:04:05Z" (now) "UTC") .Values.configs.secret.argocdServerAdminPasswordMtime | b64enc }}
  {{- end }}
  {{- range $key, $value := .Values.configs.secret.extra }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  server.secretkey: d2JuMDRVT3lidjQvclN2RGVrUjFhdjNIdzJYSll5NWZ4S214NUFIVHZmVT0=
