{{- with .Values.filebeat }}
{{- if .enabled }}
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ $.Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  type: filebeat
  version: {{ tpl .version $ }}
  kibanaRef:
    name: {{ $.Release.Name }}
  config:
    filebeat:
      autodiscover:
        {{- .autodiscover | toYaml | nindent 8 }}
    processors:
        {{- concat .processors .extraProcessors | toYaml | nindent 6 }}
    output.logstash:
      enabled: true
      loadbalance: true
      hosts: 
        - elastic-operator-ls-api.monitoring.svc:5044
  daemonSet:
    podTemplate:
      metadata:
        annotations:
          checksum/users: {{ include (print $.Template.BasePath "/eks-stack/elasticsearch-users.yaml") $ | sha256sum | substr 0 50 }}
          checksum/roles: {{ include (print $.Template.BasePath "/eks-stack/elasticsearch-roles.yaml") $ | sha256sum | substr 0 50 }}
      spec:
        # needed for autodiscover
        # see: https://github.com/elastic/cloud-on-k8s/blob/5937685b9085a5b185dde3d31ad50ccb5cdc034b/config/recipes/beats/filebeat_autodiscover.yaml
        serviceAccountName: {{ $.Release.Name }}-filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        securityContext:
          runAsUser: 0
        {{- if .tolerations }}
        tolerations:
          {{- .tolerations | toYaml | indent 10 }}
        {{- end }}
        containers:
        - name: filebeat
          resources:
            {{- .resources | toYaml | nindent 12}}
          env:
            {{- tpl (.env | toYaml) $ | nindent 10 }}
            {{- if .extraEnv }}
              {{- .extraEnv | toYaml | nindent 10 }}
            {{- end }}
          volumeMounts:
            {{- .volumeMounts | toYaml | nindent 10}}
            {{- if .extraVolumeMounts }}
              {{- .extraVolumeMounts | toYaml | nindent 10 }}
            {{- end }}
        volumes:
          {{- .volumes | toYaml | nindent 8 }}
          {{- if .extraVolumes }}
            {{- .extraVolumes | toYaml | nindent 8 }}
          {{- end -}}

{{- end }}
{{- end }}
